port = ${FEDERATION_PORT}

[queries]
federation = "SELECT account_id as id FROM Users WHERE username = ? AND domain = ?"
reverse-federation = "SELECT username as name, domain FROM Users WHERE account_id = ?"

[database]
type = "${FEDERATION_DB_TYPE}"
dsn = "${FEDERATION_DB_DSN}"
