port = ${FEDERATION_PORT}

[queries]
federation = "SELECT id FROM people WHERE name = ? AND domain = ?"
reverse-federation = "SELECT name, domain FROM people WHERE id = ?"

[database]
type = "${FEDERATION_DB_TYPE}"
dsn = "${FEDERATION_DB_DSN}"
