port = ${FEDERATION_PORT}

[queries]
federation = "SELECT id FROM users WHERE name = ? AND domain = ?"
reverse-federation = "SELECT username as name, domain FROM users WHERE account_id = ?"

[database]
type = "${FEDERATION_DB_TYPE}"
dsn = "${FEDERATION_DB_DSN}"
